#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Set-Object
Version  : 1.39
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/R/RU/RURBAN/Set-Object-1.39.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RU/RURBAN/Set-Object-1.39.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libset-object-perl/libset-object-perl_1.39-1.debian.tar.xz
Summary  : 'Unordered collections (sets) of Perl Objects'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Set-Object-lib
Requires: perl-Set-Object-license
Requires: perl-Set-Object-man

%description
~~~~~~~~~~~~~~~~~~~~~~
Set::Object provides efficient sets,
unordered collections of Perl objects without duplicates
for scalars and references.

%package lib
Summary: lib components for the perl-Set-Object package.
Group: Libraries
Requires: perl-Set-Object-license

%description lib
lib components for the perl-Set-Object package.


%package license
Summary: license components for the perl-Set-Object package.
Group: Default

%description license
license components for the perl-Set-Object package.


%package man
Summary: man components for the perl-Set-Object package.
Group: Default

%description man
man components for the perl-Set-Object package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Set-Object-1.39
mkdir -p %{_topdir}/BUILD/Set-Object-1.39/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Set-Object-1.39/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Set-Object
cp LICENSE %{buildroot}/usr/share/doc/perl-Set-Object/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Set/Object.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Set/Object/Weak.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Set/Object/autosplit.ix

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Set/Object/Object.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Set-Object/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Set::Changes.3
/usr/share/man/man3/Set::Object.3
/usr/share/man/man3/Set::Object::Weak.3
